Repository SB03-otboo-team1/sb03-otboo-team1, pull requests merged in 2025-09, with the labels that each got.

#32 [Feature] 사용자 등록(회원가입) 기능 구현
  build.gradle
  src/main/java/com/onepiece/otboo/domain/profile/repository/ProfileRepository.java
  src/main/java/com/onepiece/otboo/domain/user/api/UserApi.java
  src/main/java/com/onepiece/otboo/domain/user/controller/UserController.java
  src/main/java/com/onepiece/otboo/domain/user/controller/api/UserApi.java
  src/main/java/com/onepiece/otboo/domain/user/dto/request/UserCreateRequest.java
  src/main/java/com/onepiece/otboo/domain/user/dto/response/UserDto.java
  src/main/java/com/onepiece/otboo/domain/user/exception/DuplicateEmailException.java
  src/main/java/com/onepiece/otboo/domain/user/mapper/UserMapper.java
  src/main/java/com/onepiece/otboo/domain/user/repository/UserRepository.java
  src/main/java/com/onepiece/otboo/domain/user/service/UserService.java
  src/main/java/com/onepiece/otboo/domain/user/service/UserServiceImpl.java
  src/main/java/com/onepiece/otboo/global/config/Config.java
  src/main/java/com/onepiece/otboo/global/config/JpaConfig.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/main/java/com/onepiece/otboo/infra/security/config/SecurityConfig.java
  src/test/java/com/onepiece/otboo/domain/user/controller/UserControllerTest.java
  src/test/java/com/onepiece/otboo/domain/user/service/UserServiceImplTest.java
Labels: Feature

#37 [Feature] 피드 등록 엔티티/레포지토리 및 요청/응답 DTO 추가
  src/main/java/com/onepiece/otboo/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/onepiece/otboo/domain/feed/dto/response/AuthorDto.java
  src/main/java/com/onepiece/otboo/domain/feed/dto/response/FeedResponse.java
  src/main/java/com/onepiece/otboo/domain/feed/dto/response/OotdDto.java
  src/main/java/com/onepiece/otboo/domain/feed/entity/Feed.java
  src/main/java/com/onepiece/otboo/domain/feed/entity/FeedClothes.java
  src/main/java/com/onepiece/otboo/domain/feed/repository/FeedClothesRepository.java
  src/main/java/com/onepiece/otboo/domain/feed/repository/FeedRepository.java
Labels: Feature

#38 [Feature] Follow 생성 기능 구현
  src/main/java/com/onepiece/otboo/domain/follow/controller/FollowController.java
  src/main/java/com/onepiece/otboo/domain/follow/controller/api/FollowApi.java
  src/main/java/com/onepiece/otboo/domain/follow/dto/data/FollowData.java
  src/main/java/com/onepiece/otboo/domain/follow/dto/request/FollowRequest.java
  src/main/java/com/onepiece/otboo/domain/follow/dto/response/FollowResponse.java
  src/main/java/com/onepiece/otboo/domain/follow/entity/Follow.java
  src/main/java/com/onepiece/otboo/domain/follow/exception/FollowException.java
  src/main/java/com/onepiece/otboo/domain/follow/mapper/FollowMapper.java
  src/main/java/com/onepiece/otboo/domain/follow/repository/FollowRepository.java
  src/main/java/com/onepiece/otboo/domain/follow/service/FollowService.java
  src/main/java/com/onepiece/otboo/domain/follow/service/FollowServiceImpl.java
  src/test/java/com/onepiece/otboo/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/onepiece/otboo/domain/follow/entity/FollowTest.java
  src/test/java/com/onepiece/otboo/domain/follow/fixture/FollowFixture.java
  src/test/java/com/onepiece/otboo/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/onepiece/otboo/domain/follow/service/FollowServiceImplTest.java
Labels: Feature

#44 [Chore] 엔티티 추가 관련 DataSeeder 수정
  src/main/java/com/onepiece/otboo/infra/seeder/FeedsTableSeeder.java
  src/main/java/com/onepiece/otboo/infra/seeder/FollowsTableSeeder.java
Labels: configuration

#47 [Feature] 날씨 위치 정보 조회
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/onepiece/otboo/domain/location/dto/data/LocationDto.java
  src/main/java/com/onepiece/otboo/domain/location/exception/InvalidAreaException.java
  src/main/java/com/onepiece/otboo/domain/location/exception/InvalidCoordinateException.java
  src/main/java/com/onepiece/otboo/domain/location/exception/LocationException.java
  src/main/java/com/onepiece/otboo/domain/location/service/LocationPersistenceService.java
  src/main/java/com/onepiece/otboo/domain/location/service/LocationService.java
  src/main/java/com/onepiece/otboo/domain/location/service/LocationServiceImpl.java
  src/main/java/com/onepiece/otboo/domain/weather/controller/WeatherController.java
  src/main/java/com/onepiece/otboo/domain/weather/controller/api/WeatherApi.java
  src/main/java/com/onepiece/otboo/domain/weather/dto/data/WeatherAPILocation.java
  src/main/java/com/onepiece/otboo/domain/weather/dto/response/WeatherDto.java
  src/main/java/com/onepiece/otboo/domain/weather/service/WeatherService.java
  src/main/java/com/onepiece/otboo/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/onepiece/otboo/global/config/WebClientConfig.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/main/java/com/onepiece/otboo/infra/api/dto/KakaoLocationItem.java
  src/main/java/com/onepiece/otboo/infra/api/provider/KakaoLocationProvider.java
  src/main/java/com/onepiece/otboo/infra/api/provider/LocationProvider.java
  src/main/java/com/onepiece/otboo/infra/converter/LatLonToXYConverter.java
  src/main/java/com/onepiece/otboo/infra/security/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/test/java/com/onepiece/otboo/domain/location/service/LocationPersistenceServiceTest.java
  src/test/java/com/onepiece/otboo/domain/location/service/LocationServiceImplTest.java
  src/test/java/com/onepiece/otboo/domain/weather/controller/WeatherControllerTest.java
  src/test/java/com/onepiece/otboo/infra/api/provider/KakaoLocationProviderTest.java
  src/test/java/com/onepiece/otboo/infra/converter/LatLonToXYConverterTest.java
Labels: Feature

#50 [Chore] 정적 리소스 업데이트 2.0.2
  src/main/resources/static/assets/index-BDHebkH-.js
  src/main/resources/static/assets/index-BgUGLhLd.css
  src/main/resources/static/assets/index-BogyKWzh.css
  src/main/resources/static/assets/index-gfnTFLQG.js
  src/main/resources/static/index.html
Labels: documentation

#52 [Feature] 피드 등록 API/서비스 구현 및 테스트
  src/main/java/com/onepiece/otboo/domain/feed/controller/FeedController.java
  src/main/java/com/onepiece/otboo/domain/feed/controller/api/FeedApi.java
  src/main/java/com/onepiece/otboo/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/onepiece/otboo/domain/feed/mapper/FeedMapper.java
  src/main/java/com/onepiece/otboo/domain/feed/service/FeedService.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/onepiece/otboo/domain/feed/service/FeedServiceTest.java
Labels: Feature

#54 [Feature] Follow 요약 정보 조회
  src/main/java/com/onepiece/otboo/domain/follow/controller/FollowController.java
  src/main/java/com/onepiece/otboo/domain/follow/controller/api/FollowApi.java
  src/main/java/com/onepiece/otboo/domain/follow/dto/response/FollowSummaryResponse.java
  src/main/java/com/onepiece/otboo/domain/follow/entity/Follow.java
  src/main/java/com/onepiece/otboo/domain/follow/exception/DuplicateFollowException.java
  src/main/java/com/onepiece/otboo/domain/follow/repository/FollowRepository.java
  src/main/java/com/onepiece/otboo/domain/follow/service/FollowService.java
  src/main/java/com/onepiece/otboo/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/test/java/com/onepiece/otboo/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/onepiece/otboo/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/onepiece/otboo/domain/follow/service/FollowServiceImplTest.java
Labels: Feature

#59 [Feature] Location 중복 저장 방지 기능 추가
  src/main/java/com/onepiece/otboo/domain/location/repository/LocationRepository.java
  src/main/java/com/onepiece/otboo/domain/location/service/LocationPersistenceService.java
  src/main/java/com/onepiece/otboo/domain/location/service/LocationServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/onepiece/otboo/domain/location/fixture/LocationFixture.java
  src/test/java/com/onepiece/otboo/domain/location/service/LocationPersistenceServiceTest.java
  src/test/java/com/onepiece/otboo/domain/location/service/LocationServiceImplTest.java
Labels: Feature

#61 [Feature] 피드 삭제 기능
  src/main/java/com/onepiece/otboo/domain/feed/controller/FeedController.java
  src/main/java/com/onepiece/otboo/domain/feed/controller/api/FeedApi.java
  src/main/java/com/onepiece/otboo/domain/feed/service/FeedService.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/onepiece/otboo/domain/feed/service/FeedServiceTest.java
Labels: Feature

#73 [Fix] 실패하던 테스트 수정
  src/main/java/com/onepiece/otboo/global/dto/response/CursorPageResponseDto.java
  src/test/java/com/onepiece/otboo/domain/location/service/LocationPersistenceServiceTest.java
  src/test/java/com/onepiece/otboo/domain/location/service/LocationServiceImplTest.java
  src/test/java/com/onepiece/otboo/domain/user/controller/UserControllerTest.java
  src/test/java/com/onepiece/otboo/domain/user/service/UserServiceImplTest.java
  src/test/java/com/onepiece/otboo/domain/weather/controller/WeatherControllerTest.java
  src/test/java/com/onepiece/otboo/domain/weather/service/WeatherServiceImplTest.java
  src/test/java/com/onepiece/otboo/infra/api/provider/KakaoLocationProviderTest.java
  src/test/java/com/onepiece/otboo/infra/api/provider/KmaWeatherProviderTest.java
Labels: bug

#79 [Feature] 어드민 기능
  .github/workflows/ci.yml
  src/integrationTest/java/com/onepiece/otboo/domain/auth/AdminFeatureIntegrationTest.java
  src/integrationTest/java/com/onepiece/otboo/domain/weather/batch/config/WeatherBatchConfigTest.java
  src/main/java/com/onepiece/otboo/domain/auth/controller/api/AuthApi.java
  src/main/java/com/onepiece/otboo/domain/profile/entity/Profile.java
  src/main/java/com/onepiece/otboo/domain/user/controller/UserController.java
  src/main/java/com/onepiece/otboo/domain/user/controller/api/UserApi.java
  src/main/java/com/onepiece/otboo/domain/user/dto/request/UserLockUpdateRequest.java
  src/main/java/com/onepiece/otboo/domain/user/dto/request/UserRoleUpdateRequest.java
  src/main/java/com/onepiece/otboo/domain/user/service/UserService.java
  src/main/java/com/onepiece/otboo/domain/user/service/UserServiceImpl.java
  src/main/java/com/onepiece/otboo/infra/security/auth/CustomAuthenticationProvider.java
  src/main/java/com/onepiece/otboo/infra/seeder/AdminAccountInitializer.java
  src/main/java/com/onepiece/otboo/infra/seeder/LocationTableSeeder.java
  src/main/java/com/onepiece/otboo/infra/seeder/UserProfileTableSeeder.java
  src/main/java/com/onepiece/otboo/infra/seeder/UserTableSeeder.java
  src/main/resources/application.yaml
  src/test/java/com/onepiece/otboo/domain/user/controller/UserControllerTest.java
  src/test/java/com/onepiece/otboo/domain/user/service/UserServiceImplTest.java
  src/test/java/com/onepiece/otboo/infra/seeder/AdminAccountInitializerTest.java
Labels: Feature

#84 [Feature] 프로필 조회 기능 추가
  src/integrationTest/java/com/onepiece/otboo/domain/user/controller/UserControllerIntegrationTest.java
  src/main/java/com/onepiece/otboo/domain/profile/dto/response/ProfileDto.java
  src/main/java/com/onepiece/otboo/domain/profile/exception/ProfileException.java
  src/main/java/com/onepiece/otboo/domain/profile/exception/ProfileNotFoundException.java
  src/main/java/com/onepiece/otboo/domain/profile/mapper/ProfileMapper.java
  src/main/java/com/onepiece/otboo/domain/profile/service/ProfileService.java
  src/main/java/com/onepiece/otboo/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/onepiece/otboo/domain/user/controller/UserController.java
  src/main/java/com/onepiece/otboo/domain/user/controller/api/UserApi.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/test/java/com/onepiece/otboo/domain/profile/fixture/ProfileDtoFixture.java
  src/test/java/com/onepiece/otboo/domain/profile/fixture/ProfileFixture.java
  src/test/java/com/onepiece/otboo/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/onepiece/otboo/domain/user/controller/UserControllerTest.java
Labels: Feature

#80 [Feature] 피드 수정 기능
  src/main/java/com/onepiece/otboo/domain/feed/controller/FeedController.java
  src/main/java/com/onepiece/otboo/domain/feed/controller/api/FeedApi.java
  src/main/java/com/onepiece/otboo/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/onepiece/otboo/domain/feed/entity/Feed.java
  src/main/java/com/onepiece/otboo/domain/feed/service/FeedService.java
  src/main/java/com/onepiece/otboo/global/exception/ErrorCode.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerUpdateTest.java
  src/test/java/com/onepiece/otboo/domain/feed/service/FeedServiceUpdateTest.java
Labels: Feature

#88 [Chore] 정적 리소스 업데이트 2.0.4
  src/main/resources/static/assets/index-B6awMYOr.css
  src/main/resources/static/assets/index-BDHebkH-.js
  src/main/resources/static/assets/index-BogyKWzh.css
  src/main/resources/static/assets/index-D9OpL5Ku.js
  src/main/resources/static/index.html
Labels: documentation

#100 [Feature] 피드 목록 조회 기능
  src/main/java/com/onepiece/otboo/domain/feed/controller/FeedController.java
  src/main/java/com/onepiece/otboo/domain/feed/controller/api/FeedApi.java
  src/main/java/com/onepiece/otboo/domain/feed/enums/FeedSortBy.java
  src/main/java/com/onepiece/otboo/domain/feed/repository/FeedRepository.java
  src/main/java/com/onepiece/otboo/domain/feed/service/FeedQueryService.java
  src/main/java/com/onepiece/otboo/global/enums/SortDirection.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerListTest.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/onepiece/otboo/domain/feed/controller/FeedControllerUpdateTest.java
  src/test/java/com/onepiece/otboo/domain/feed/service/FeedQueryServiceListTest.java
Labels: Feature
